<a href="https://colab.research.google.com/github/srujanperam/pt/blob/main/torch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import numpy as np
import pandas as pd

In [7]:
mylist = [1,2,3,4,5,6,7,8,9]
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
mylist = [[1,2,3,4,5],[6,7,8,9]]
mylist

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [13]:
nump = np.random.rand(3,4)
nump

array([[0.20699243, 0.52999546, 0.28161529, 0.36465295],
       [0.82034657, 0.07425428, 0.23575904, 0.6802671 ],
       [0.78966413, 0.60319432, 0.65603672, 0.69350452]])

In [12]:
nump.dtype

dtype('float64')

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.5906,  0.7030, -0.3055,  0.4190],
        [ 1.3587, -0.3437, -0.6600, -0.7652],
        [ 0.3433,  1.6273, -0.2056, -1.4107]])

In [16]:

tensor_3d = torch.zeros(2, 3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
numptotorch = torch.tensor(nump)
numptotorch

tensor([[0.2070, 0.5300, 0.2816, 0.3647],
        [0.8203, 0.0743, 0.2358, 0.6803],
        [0.7897, 0.6032, 0.6560, 0.6935]], dtype=torch.float64)

In [18]:
numptotorch.dtype

torch.float64