<a href="https://colab.research.google.com/github/srujanperam/pt/blob/main/torch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np
import pandas as pd

In [8]:
mylist = [1,2,3,4,5,6,7,8,9]
mylist

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
mylist = [[1,2,3,4,5],[6,7,8,9]]
mylist

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [10]:
nump = np.random.rand(3,4)
nump

array([[0.86903098, 0.27728585, 0.79001852, 0.22631817],
       [0.23668917, 0.00912483, 0.19436062, 0.32376181],
       [0.71606806, 0.29406133, 0.67084654, 0.01460794]])

In [11]:
nump.dtype

dtype('float64')

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.9665,  1.2573,  0.5633, -0.8389],
        [ 0.7899,  0.2530,  0.3943, -0.2582],
        [ 1.9224,  0.4414,  1.3982,  0.4350]])

In [13]:

tensor_3d = torch.zeros(2, 3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
numptotorch = torch.tensor(nump)
numptotorch

tensor([[0.8690, 0.2773, 0.7900, 0.2263],
        [0.2367, 0.0091, 0.1944, 0.3238],
        [0.7161, 0.2941, 0.6708, 0.0146]], dtype=torch.float64)

In [15]:
numptotorch.dtype

torch.float64

In [16]:
mytorch = torch.arange(10)
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
mytorch.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
mytorch.reshape(2,6)

RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [18]:
mytorch.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
mytorch = torch.arange(15)

In [20]:
mytorch.reshape(-1,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [21]:
mytorch.reshape(-1)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
mytorch.view(3,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
mytorch = torch.arange(10)
mytorch[7]

tensor(7)

In [24]:
mytorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
mytorch.shape

torch.Size([10])